<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAabixt7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAabixt7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAabixt7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAabixt7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAabixt7\srcDevDebugProjectContainer([
    'container.build_hash' => 'Aabixt7',
    'container.build_id' => 'f092745e',
    'container.build_time' => 1553007080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAabixt7');
