<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtwpvhd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtwpvhd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWtwpvhd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWtwpvhd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWtwpvhd\srcDevDebugProjectContainer([
    'container.build_hash' => 'Wtwpvhd',
    'container.build_id' => '7dd007a2',
    'container.build_time' => 1553003737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtwpvhd');
